name: Docker Image CI

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Build the Docker image
      run: docker build . --tag idrinth/walled-secrets:latest
    - name: Login to Docker Hub
      run: docker login --username $DOCKER_HUB_LOGIN --password $DOCKER_HUB_PASSWORD
    - name: Share the Docker image
      run: docker push idrinth/walled-secrets:latest
