name: Docker Image CI

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Build the Docker image
      run: docker build . --tag idrinth/walled-secrets:latest
    - name: Share the Docker image
      run: docker push idrinth/walled-secrets:latest
