name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_LOGIN }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - uses: actions/checkout@v3
      with:
        ref: ${{ tag }}
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Build the Docker image
      run: docker build . --tag idrinth/walled-secrets:${{ tag }}
    - name: Share the Docker image
      run: docker push idrinth/walled-secrets:${{ tag }}
