name: Phan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  phan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: latest
        extensions: ast
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Run phan
      run: composer run-script test-static
